spring.application.name=db-benchmark

spring.datasource.url=jdbc:h2:mem:benchmarkdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.data.mongodb.database=benchmarkdb
de.flapdoodle.mongodb.embedded.version=7.0.9

server.port=8082